Prueba_Tecnica_Poli/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prueba_Tecnica_Poli.Models;

namespace Prueba_Tecnica_Poli.Controllers
{
    public class AutorController : Controller
    {
        private readonly DbAppPoliContext _context;

        public AutorController(DbAppPoliContext context)
        {
            _context = context;
        }

        // GET: Autor
        public async Task<IActionResult> Index()
        {
            var dbAppPoliContext = _context.Autors.Include(a => a.IdTipoDoctoNavigation);
            return View(await dbAppPoliContext.ToListAsync());
        }

        // GET: Autor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Autors == null)
            {
                return NotFound();
            }

            var autor = await _context.Autors
                .Include(a => a.IdTipoDoctoNavigation)
                .FirstOrDefaultAsync(m => m.IdAutor == id);

            //var libros = _context.Autors
            //    .Include(a => a.Libros)
            //    .FirstOrDefault(a => a.IdAutor == id);

            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }

        // GET: Autor/DetailsBooks/5
        public async Task<IActionResult> DetailsBooks(int? id)
        {
            if (id == null || _context.Autors == null)
            {
                return NotFound();
            }

            var libros = _context.Autors
                .Include(a => a.Libros)
                .FirstOrDefault(a => a.IdAutor == id)?.Libros.ToList();

            if (libros == null)
            {
                return NotFound();
            }

            return View(libros);
        }

        // GET: Autor/Create
        public IActionResult Create()
        {
            ViewData["IdTipoDocto"] = new SelectList(_context.TipoDoctos, "IdTipoDocto", "Nombre");
            return View();
        }

        // POST: Autor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAutor,Nombre,Apellido,IdTipoDocto,NumDocto,FecNacimiento")] Autor autor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(autor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTipoDocto"] = new SelectList(_context.TipoDoctos, "IdTipoDocto", "Nombre", autor.IdTipoDocto);
            return View(autor);
        }

        // GET: Autor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Autors == null)
            {
                return NotFound();
            }

            var autor = await _context.Autors.FindAsync(id);
            if (autor == null)
            {
                return NotFound();
            }
            ViewData["IdTipoDocto"] = new SelectList(_context.TipoDoctos, "IdTipoDocto", "Nombre", autor.IdTipoDocto);
            return View(autor);
        }

        // POST: Autor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAutor,Nombre,Apellido,IdTipoDocto,NumDocto,FecNacimiento")] Autor autor)
        {
            if (id != autor.IdAutor)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(autor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutorExists(autor.IdAutor))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTipoDocto"] = new SelectList(_context.TipoDoctos, "IdTipoDocto", "Nombre", autor.IdTipoDocto);
            return View(autor);
        }

        // GET: Autor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Autors == null)
            {
                return NotFound();
            }

            var autor = await _context.Autors
                .Include(a => a.IdTipoDoctoNavigation)
                .FirstOrDefaultAsync(m => m.IdAutor == id);
            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }

        // POST: Autor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Autors == null)
            {
                return Problem("Entity set 'DbAppPoliContext.Autors'  is null.");
            }
            var autor = await _context.Autors.FindAsync(id);
            if (autor != null)
            {
                _context.Autors.Remove(autor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutorExists(int id)
        {
          return (_context.Autors?.Any(e => e.IdAutor == id)).GetValueOrDefault();
        }
    }
}

Prueba_Tecnica_Poli/Controllers/LibroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prueba_Tecnica_Poli.Models;

namespace Prueba_Tecnica_Poli.Controllers
{
    public class LibroController : Controller
    {
        private readonly DbAppPoliContext _context;

        public LibroController(DbAppPoliContext context)
        {
            _context = context;
        }

        // GET: Libro
        public async Task<IActionResult> Index()
        {
            var dbAppPoliContext = _context.Libros.Include(l => l.IdAutorNavigation).Include(l => l.IdEditorialNavigation);
            return View(await dbAppPoliContext.ToListAsync());
        }

        // GET: Libro/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Libros == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.IdAutorNavigation)
                .Include(l => l.IdEditorialNavigation)
                .FirstOrDefaultAsync(m => m.IdLibro == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: Libro/Create
        public IActionResult Create()
        {
            ViewData["IdAutor"] = new SelectList(_context.Autors, "IdAutor", "NombreCompleto");
            ViewData["IdEditorial"] = new SelectList(_context.Editorials, "IdEditorial", "Nombre");
            return View();
        }

        // POST: Libro/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdLibro,Titulo,IdEditorial,NumPaginas,FecPublicacion,IdAutor")] Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(libro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAutor"] = new SelectList(_context.Autors, "IdAutor", "NombreCompleto", libro.IdAutor);
            ViewData["IdEditorial"] = new SelectList(_context.Editorials, "IdEditorial", "Nombre", libro.IdEditorial);
            return View(libro);
        }

        // GET: Libro/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Libros == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros.FindAsync(id);
            if (libro == null)
            {
                return NotFound();
            }
            ViewData["IdAutor"] = new SelectList(_context.Autors, "IdAutor", "NombreCompleto", libro.IdAutor);
            ViewData["IdEditorial"] = new SelectList(_context.Editorials, "IdEditorial", "Nombre", libro.IdEditorial);
            return View(libro);
        }

        // POST: Libro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdLibro,Titulo,IdEditorial,NumPaginas,FecPublicacion,IdAutor")] Libro libro)
        {
            if (id != libro.IdLibro)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(libro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.IdLibro))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAutor"] = new SelectList(_context.Autors, "IdAutor", "NombreCompleto", libro.IdAutor);
            ViewData["IdEditorial"] = new SelectList(_context.Editorials, "IdEditorial", "Nombre", libro.IdEditorial);
            return View(libro);
        }

        // GET: Libro/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Libros == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.IdAutorNavigation)
                .Include(l => l.IdEditorialNavigation)
                .FirstOrDefaultAsync(m => m.IdLibro == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // POST: Libro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Libros == null)
            {
                return Problem("Entity set 'DbAppPoliContext.Libros'  is null.");
            }
            var libro = await _context.Libros.FindAsync(id);
            if (libro != null)
            {
                _context.Libros.Remove(libro);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LibroExists(int id)
        {
          return (_context.Libros?.Any(e => e.IdLibro == id)).GetValueOrDefault();
        }
    }
}

Prueba_Tecnica_Poli/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prueba Poli</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Prueba_Tecnica_Poli.styles.css" asp-append-version="true" />
    <!--Link a cdn de Bootstrap (bootswatch)-->
    <link rel="stylesheet" href="https://bootswatch.com/4/sketchy/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm" style="background-color: #1fb2de;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="bg-white" src="https://www.poli.edu.co/sites/default/files/logos/politecnico-grancolombiano_2.svg" width="200" height="50" alt="Politécnico Grancolombiano"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item mr-3">
                            <a class="btn btn-outline-primary rounded-pill" asp-area="" asp-controller="Home" asp-action="Index"><img width="20" height="20" src="https://img.icons8.com/ios-filled/50/home.png" alt="Home" /></a>
                        </li>
                        <li class="nav-item mr-3">
                            <a class="btn btn-outline-primary rounded-pill" asp-area="" asp-controller="Autor" asp-action="Index">Autores</a>
                        </li>
                        <li class="nav-item mr-3">
                            <a class="btn btn-outline-primary rounded-pill" asp-area="" asp-controller="Libro" asp-action="Index">Libros</a>
                        </li>
                        <li class="nav-item mr-3">
                            <a class="btn btn-outline-primary rounded-pill" asp-area="" asp-controller="Home" asp-action="Privacy">Contacto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Prueba Técnica Poli - Jonathan Borda - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>